// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace mm_lib
{
    public partial class members_managementContext : DbContext
    {
        public members_managementContext()
        {
        }

        public members_managementContext(DbContextOptions<members_managementContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Membership> Membership { get; set; }
        public virtual DbSet<Register> Register { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-LK2QAA8\\SQLEXPRESS;Initial Catalog=members_management;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Members>(entity =>
            {
                entity.HasKey(e => e.MemberId)
                    .HasName("PK__Members__0CF04B180900EFB7");

                entity.Property(e => e.Dob).HasColumnType("date");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PhoneNo)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.HasOne(d => d.Org)
                    .WithMany(p => p.Members)
                    .HasForeignKey(d => d.OrgId)
                    .HasConstraintName("FK__Members__OrgId__38996AB5");
            });

            modelBuilder.Entity<Membership>(entity =>
            {
                entity.Property(e => e.StartDate).HasColumnType("date");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Membership)
                    .HasForeignKey(d => d.MemberId)
                    .HasConstraintName("FK__Membershi__Membe__4AB81AF0");

                entity.HasOne(d => d.Org)
                    .WithMany(p => p.Membership)
                    .HasForeignKey(d => d.OrgId)
                    .HasConstraintName("FK__Membershi__OrgId__49C3F6B7");
            });

            modelBuilder.Entity<Register>(entity =>
            {
                entity.HasKey(e => e.OrgId)
                    .HasName("PK__Register__420C9E6C2F3BF5B4");

                entity.Property(e => e.Email)
                    .HasMaxLength(75)
                    .IsUnicode(false);

                entity.Property(e => e.OrgName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Password)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}