// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mm_lib
{
    public partial class Membership
    {
        public long MembershipId { get; set; }
        public long? OrgId { get; set; }
        public long? MemberId { get; set; }
        public DateTime? StartDate { get; set; }
        public int? Duration { get; set; }
        public long? AmountPaid { get; set; }
        public bool? PaymentStatus { get; set; }

        public virtual Members Member { get; set; }
        public virtual Register Org { get; set; }
    }
}