// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace mm_lib
{
    public partial class Members
    {
        public Members()
        {
            Membership = new HashSet<Membership>();
        }

        public long MemberId { get; set; }
        public long? OrgId { get; set; }
        public string Name { get; set; }
        [Phone(ErrorMessage = "Invalid PhoneNo")]
        public string PhoneNo { get; set; }
        public DateTime? Dob { get; set; }
        public bool? Gender { get; set; }

        public virtual Register Org { get; set; }
        public virtual ICollection<Membership> Membership { get; set; }
    }
}